version: "3.9"
services:
  tailscale-plex:
    image: tailscale/tailscale:latest # Image to be used
    container_name: tailscale-plex # Name for local container management
    hostname: plex # Name used within your Tailscale environment
    environment:
      - TS_AUTHKEY=$TS_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      #- TS_SERVE_CONFIG=/config/serve.json # Tailsacale Serve configuration to expose the web interface on your local Tailnet - remove this line if not required
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--ssh
    volumes:
      - /docker_config/plex:/config
      - /mnt:/data
      - /docker_config/incomplete-downloads:/incomplete-downloads
      - /docker_config/plex-state/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    cap_add:
      - net_admin # Tailscale requirement
      - sys_module # Tailscale requirement
    ports:
      - 0.0.0.0:32400:32400
      - 0.0.0.0:8324:8324
      - 0.0.0.0:32469:32469
      - 0.0.0.0:1900:1900/udp
      - 0.0.0.0:32410:32410/udp
      - 0.0.0.0:32412:32412/udp
      - 0.0.0.0:32413:32413/udp
      - 0.0.0.0:32414:32414/udp

  plex:
    container_name: plex
    network_mode: service:tailscale-plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - TZ=Australia/Brisbane
      - PLEX_CLAIM=claim-my8UMCgsJ-bnPYWfYYp3
      - ADVERTISE_IP=http://192.168.1.103:32400/
    volumes:
      - /docker_config/plex:/config
      - /mnt:/data
      - /docker_config/plex-transcode:/transcode
    depends_on:
      - tailscale-plex

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker_config/watchtower:/config
    command: --interval 86400 --debug
    restart: unless-stopped
    environment:
      - TZ=Australia/Brisbane
    depends_on:
      - tailscale-plex
