version: "3.9"
services:
  tailscale-plex:
    image: tailscale/tailscale:latest # Image to be used
    container_name: tailscale-plex # Name for local container management
    hostname: arrs # Name used within your Tailscale environment
    environment:
      - TS_AUTHKEY=$TS_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_EXTRA_ARGS=--ssh
    volumes:
      - /docker_config/arrs:/config
      - /mnt:/data
      - /docker_config/incomplete-downloads:/incomplete-downloads
      - /docker_config/arrs-state/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    cap_add:
      - net_admin # Tailscale requirement
      - sys_module # Tailscale requirement
    ports:
      - 0.0.0.0:8383:8383 # SABNZBD
      - 0.0.0.0:9393:9393 # SABNZBD
      - 0.0.0.0:8989:8989 # SONARR
      - 0.0.0.0:7878:7878 # RADARR
      - 0.0.0.0:8191:8191 # FLARESOLVERR
      - 0.0.0.0:5055:5055 # OVERSEERR
      - 0.0.0.0:8181:8181 # TAUTULLI
      - 0.0.0.0:9696:9696 # PROWLARR
      - 0.0.0.0:81:81     # NGINXPROXYMANAGER
      - 0.0.0.0:80:80     # NGINXPROXYMANAGER
      - 0.0.0.0:443:443   # NGINXPROXYMANAGER
    healthcheck:
      test: ["CMD", "tailscale", "status"] # Check if Tailscale is running
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: always

  plex:
    container_name: plex
    network_mode: service:tailscale-plex
    image: plexinc/pms-docker
    restart: unless-stopped
    environment:
      - PUID=1005
      - PGID=1005
      - TZ=Australia/Brisbane
      - PLEX_CLAIM=$PLEX_CLAIM
      - ADVERTISE_IP=http://192.168.1.103:32400/
    volumes:
      - /docker_config/plex:/config
      - /mnt:/data
      - /docker_config/plex-transcode:/transcode
    depends_on:
      - tailscale-plex

  pihole:
    container_name: pihole
    shm_size: '4gb'
    image: pihole/pihole:2025.06.2
    network_mode: service:tailscale-plex
    environment:
      - PUID=1005
      - PGID=1005
      - PIHOLE_UID=1005
      - PIHOLE_GID=1005
      - TZ=Australia/Brisbane
    # Volumes store your data between container upgrades
    volumes:
      - '/docker_config/pihole:/etc/pihole'
      - '/root/.acme.sh/pihole.jonny.blue_ecc:/etc/letsencrypt'
    cap_add:
      - NET_ADMIN
      - CAP_SYS_TIME
      - CAP_SYS_NICE
      - SYS_TIME
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /docker_config/watchtower:/config
    command: --interval 86400 --debug
    restart: unless-stopped
    environment:
      - TZ=Australia/Brisbane
    depends_on:
      - tailscale-plex
